---
metric_prefix: "cloudwatch"
influx_host: "influxdb.news.cloud.bbc.co.uk"
influx_port: 2003
metric_types:
-
  namespace: "AWS/EC2"
  ec2_component: "BBCComponent"
  metric_name: "general-election-2015-renderer"
  metrics:
    -
      name: "CPUUtilization"
      unit: "Percent"
      statistics:
        - Average
    -
      name: "NetworkIn"
      unit: "Bytes"
      statistics:
        - Average
    -
      name: "NetworkOut"
      unit: "Bytes"
      statistics:
        - Average
-
  namespace: "AWS/EC2"
  ec2_component: "BBCComponent"
  metric_name: "general-election-2015-broker"
  metrics:
    -
      name: "CPUUtilization"
      unit: "Percent"
      statistics:
        - Average
    -
      name: "NetworkIn"
      unit: "Bytes"
      statistics:
        - Average
    -
      name: "NetworkOut"
      unit: "Bytes"
      statistics:
        - Average
