---
metric_prefix: "cloudwatch"
influx_options:
  influx_host: "influxdb.domain.com"
  influx_database: cloudwatch
  influx_ssl: true
  influx_verify_ssl: true
  influx_ssl_ca_cert: "/path/to/certs"
  influx_username: "username"
  influx_password: "password"

metric_types:
## EC2 Metrics
-
  namespace: "AWS/EC2"
  ec2_tag_key: "BBCComponent"
  ec2_tag_value: "newsbeat-composition"
  metrics:
    -
      name: "CPUUtilization"
      unit: "Percent"
      statistics:
        - Average
    -
      name: "NetworkIn"
      unit: "Bytes"
      statistics:
        - Average
    -
      name: "NetworkOut"
      unit: "Bytes"
      statistics:
        - Average

## Custom Metrics
-
  namespace: "BBCApp/newsbeat/live"
  metrics:
    -
      name: "Headline301Redirect"
      unit: "Count"
      statistics:
        - Sum
    -
      name: "InvalidHeadline"
      unit: "Count"
      statistics:
        - Sum
    -
      name: "LegacyArticle"
      unit: "Count"
      statistics:
        - Sum

## SQS Metrics
-
  namespace: "AWS/SQS"
  queue_name: "live-news-ArticleQueue-N7RAX00100RC"
  metrics:
    -
      name: "ApproximateNumberOfMessagesVisible"
      unit: "Count"
      statistics:
        - Sum
    -
      name: "NumberOfMessagesDeleted"
      unit: "Count"
      statistics:
        - Sum
